global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/prometheus-djorm/metrics'
    static_configs:
      - targets: [host.docker.internal:8000]